// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperatureSensorApi.Data;

#nullable disable

namespace TemperatureSensorApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230917131908_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("TemperatureSensorApi.Models.TemperatureHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<int>("TemperatureStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("HistoryList");
                });

            modelBuilder.Entity("TemperatureSensorApi.Models.TemperatureSensor", b =>
                {
                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("TemperatureSensor");
                });

            modelBuilder.Entity("TemperatureSensorApi.Models.TemperatureStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TemperatureStatusList");
                });
#pragma warning restore 612, 618
        }
    }
}
